-- Animatoru tērpi (tēli pasākumu rezervācijas formā): esošie 109 ieraksti,
-- tie paši, kas šobrīd ir mājaslapas kodā (data/animatorCharacters.ts).
-- Palaid PĒC schema.sql: SQL Editor -> ielīmē visu failu -> Run.
-- Sadaļa tiek aizpildīta tikai tad, ja tajā vēl nav neviena ieraksta,
-- tāpēc skriptu var droši palaist atkārtoti.

insert into public.section_items (section_key, title, image_url, sort_order)
select * from (values
  ('animatoru-terpi', 'Anna', '/kostimi/princesses/anna.jpg', 10),
  ('animatoru-terpi', 'Barbie', '/kostimi/princesses/barbie.jpg', 20),
  ('animatoru-terpi', 'Bella', '/kostimi/princesses/bella.jpg', 30),
  ('animatoru-terpi', 'Feja', '/kostimi/princesses/feja-1.jpg', 40),
  ('animatoru-terpi', 'Feja 2', '/kostimi/princesses/feja-2.jpg', 50),
  ('animatoru-terpi', 'Elza', '/kostimi/princesses/frozen-1.jpg', 60),
  ('animatoru-terpi', 'Elza 2', '/kostimi/princesses/frozen-2.jpg', 70),
  ('animatoru-terpi', 'Nārina', '/kostimi/princesses/narina.jpg', 80),
  ('animatoru-terpi', 'Princese', '/kostimi/princesses/princese.jpg', 90),
  ('animatoru-terpi', 'Princese Zeltīte', '/kostimi/princesses/princese-zeltite.jpg', 100),
  ('animatoru-terpi', 'Princis', '/kostimi/princesses/princis.jpg', 110),
  ('animatoru-terpi', 'Salātlapiņa', '/kostimi/princesses/salatlapina.jpg', 120),
  ('animatoru-terpi', 'Batgirl', '/kostimi/supervaroni/batgirl.jpg', 130),
  ('animatoru-terpi', 'Betmens', '/kostimi/supervaroni/betmens.jpg', 140),
  ('animatoru-terpi', 'Halks', '/kostimi/supervaroni/halks.jpg', 150),
  ('animatoru-terpi', 'Iron Man', '/kostimi/supervaroni/iron-man.jpg', 160),
  ('animatoru-terpi', 'Kaķsieviete', '/kostimi/supervaroni/kaksieviete.jpg', 170),
  ('animatoru-terpi', 'Kapteinis Amerika', '/kostimi/supervaroni/kapteinis-amerika.jpg', 180),
  ('animatoru-terpi', 'Lady Bug', '/kostimi/supervaroni/lady-bug.jpg', 190),
  ('animatoru-terpi', 'Melnā Pantera', '/kostimi/supervaroni/melna-pantera.jpg', 200),
  ('animatoru-terpi', 'Spiderman', '/kostimi/supervaroni/spiderman.jpg', 210),
  ('animatoru-terpi', 'Supermeitene', '/kostimi/supervaroni/super-meitene.jpg', 220),
  ('animatoru-terpi', 'Supermens', '/kostimi/supervaroni/supermens.jpg', 230),
  ('animatoru-terpi', 'Thors', '/kostimi/supervaroni/thors.jpg', 240),
  ('animatoru-terpi', 'Wolverine', '/kostimi/supervaroni/wolverine.jpg', 250),
  ('animatoru-terpi', 'Zibsnis', '/kostimi/supervaroni/zibsnis-1.jpg', 260),
  ('animatoru-terpi', 'Zibsnis 2', '/kostimi/supervaroni/zibsnis-2.jpg', 270),
  ('animatoru-terpi', 'Ash', '/kostimi/multfilmu/ash-no-pokemoniem.jpg', 280),
  ('animatoru-terpi', 'Avatars', '/kostimi/multfilmu/avatars.jpg', 290),
  ('animatoru-terpi', 'Bailīgā Mūķene', '/kostimi/multfilmu/bailiga-mukene.jpg', 300),
  ('animatoru-terpi', 'Bings', '/kostimi/multfilmu/bings.jpg', 310),
  ('animatoru-terpi', 'Čeizs', '/kostimi/multfilmu/ceizs.jpg', 320),
  ('animatoru-terpi', 'Minecraft Creeper', '/kostimi/multfilmu/creeper-no-minecraft.jpg', 330),
  ('animatoru-terpi', 'Cruella', '/kostimi/multfilmu/cruella.jpg', 340),
  ('animatoru-terpi', 'Dino mazulis', '/kostimi/multfilmu/Dino mazulis.jpg', 350),
  ('animatoru-terpi', 'Drakula', '/kostimi/multfilmu/drakula.jpg', 360),
  ('animatoru-terpi', 'Džokers', '/kostimi/multfilmu/dzokers-1.jpg', 370),
  ('animatoru-terpi', 'Everesta', '/kostimi/multfilmu/everesta.jpg', 380),
  ('animatoru-terpi', 'Fins', '/kostimi/multfilmu/fins.jpg', 390),
  ('animatoru-terpi', 'Gabby', '/kostimi/multfilmu/gabbu-dollhouse.jpg', 400),
  ('animatoru-terpi', 'Harijs Poters', '/kostimi/multfilmu/Harijs potters.jpg', 410),
  ('animatoru-terpi', 'Hermione', '/kostimi/multfilmu/Hermione.jpg', 420),
  ('animatoru-terpi', 'Hello Kitty', '/kostimi/multfilmu/hello-kitty.jpg', 430),
  ('animatoru-terpi', 'Joy', '/kostimi/multfilmu/joy.jpg', 440),
  ('animatoru-terpi', 'Klauns', '/kostimi/multfilmu/klauns.jpg', 450),
  ('animatoru-terpi', 'Labubu', '/kostimi/multfilmu/labubu-lilla.jpg', 460),
  ('animatoru-terpi', 'Labubu Rozā', '/kostimi/multfilmu/labubu-roza.jpg', 470),
  ('animatoru-terpi', 'Lego Ninjago', '/kostimi/multfilmu/lego-ninjago.jpg', 480),
  ('animatoru-terpi', 'LOL Balerīna', '/kostimi/multfilmu/lol-balerina.jpg', 490),
  ('animatoru-terpi', 'LOL Queen Bee', '/kostimi/multfilmu/lol-queen-bee.jpg', 500),
  ('animatoru-terpi', 'Luigi', '/kostimi/multfilmu/luigi.jpg', 510),
  ('animatoru-terpi', 'Maršels', '/kostimi/multfilmu/marsels.jpg', 520),
  ('animatoru-terpi', 'Maša', '/kostimi/multfilmu/Masa-un-lacis.jpg', 530),
  ('animatoru-terpi', 'Minioni', '/kostimi/multfilmu/minioni.jpg', 540),
  ('animatoru-terpi', 'Minnija', '/kostimi/multfilmu/minnija.jpg', 550),
  ('animatoru-terpi', 'Money Heist', '/kostimi/multfilmu/money-heist-1.jpg', 560),
  ('animatoru-terpi', 'Pennywise', '/kostimi/multfilmu/pennywise.jpg', 570),
  ('animatoru-terpi', 'Pepija Garzeķe', '/kostimi/multfilmu/pepija-garzeke.jpg', 580),
  ('animatoru-terpi', 'Peppa', '/kostimi/multfilmu/peppa.jpg', 590),
  ('animatoru-terpi', 'Pikachu', '/kostimi/multfilmu/pikacu.jpg', 600),
  ('animatoru-terpi', 'Pirāte', '/kostimi/multfilmu/pirata-meitene.jpg', 610),
  ('animatoru-terpi', 'Pirāts', '/kostimi/multfilmu/pirata-zens-1.jpg', 620),
  ('animatoru-terpi', 'Pomni', '/kostimi/multfilmu/pomnija.jpg', 630),
  ('animatoru-terpi', 'Poppy', '/kostimi/multfilmu/poppija.jpg', 640),
  ('animatoru-terpi', 'Ragana', '/kostimi/multfilmu/ragana.jpg', 650),
  ('animatoru-terpi', 'Selestija', '/kostimi/multfilmu/selestija-vienradzis.jpg', 660),
  ('animatoru-terpi', 'Simka', '/kostimi/multfilmu/simka-no-fiksiki.jpg', 670),
  ('animatoru-terpi', 'Skaja', '/kostimi/multfilmu/skaja.jpg', 680),
  ('animatoru-terpi', 'Smurfete', '/kostimi/multfilmu/smurfete.jpg', 690),
  ('animatoru-terpi', 'Soniks', '/kostimi/multfilmu/soniks.jpg', 700),
  ('animatoru-terpi', 'Spociņš', '/kostimi/multfilmu/spocins.jpg', 710),
  ('animatoru-terpi', 'Šreks', '/kostimi/multfilmu/sreks.jpg', 720),
  ('animatoru-terpi', 'Stičs', '/kostimi/multfilmu/stich.jpg', 730),
  ('animatoru-terpi', 'Sūklis Bobs', '/kostimi/multfilmu/suklis-bobs-1.jpg', 740),
  ('animatoru-terpi', 'Super Mario', '/kostimi/multfilmu/supermario.jpg', 750),
  ('animatoru-terpi', 'Transformers', '/kostimi/multfilmu/transformer.jpg', 760),
  ('animatoru-terpi', 'Ninja Turtles', '/kostimi/multfilmu/turtles-ninja.jpg', 770),
  ('animatoru-terpi', 'Twilight Sparkle', '/kostimi/multfilmu/twilight-sparkle-unicorn.jpg', 780),
  ('animatoru-terpi', 'Vienradzis', '/kostimi/multfilmu/vienradzis.jpg', 790),
  ('animatoru-terpi', 'Vinnijs Pūks', '/kostimi/multfilmu/vinnijs.jpg', 800),
  ('animatoru-terpi', 'Wednesday', '/kostimi/multfilmu/wednesday.jpg', 810),
  ('animatoru-terpi', 'Bembijs', '/kostimi/dzivnieki/bembijs.jpg', 820),
  ('animatoru-terpi', 'Bite', '/kostimi/dzivnieki/bite.jpg', 830),
  ('animatoru-terpi', 'Bitīte', '/kostimi/dzivnieki/bitite.jpg', 840),
  ('animatoru-terpi', 'Lācis', '/kostimi/dzivnieki/lacis.jpg', 850),
  ('animatoru-terpi', 'Lapsa', '/kostimi/dzivnieki/lapsa-krumins.jpg', 860),
  ('animatoru-terpi', 'Lauva', '/kostimi/dzivnieki/lauva.jpg', 870),
  ('animatoru-terpi', 'Runcis', '/kostimi/dzivnieki/runcis.jpg', 880),
  ('animatoru-terpi', 'Zaķis', '/kostimi/dzivnieki/zakis-1.jpg', 890),
  ('animatoru-terpi', 'Žirafe', '/kostimi/dzivnieki/zirafe.jpg', 900),
  ('animatoru-terpi', 'Bruņinieks', '/kostimi/profesijas/bruninieks.jpg', 910),
  ('animatoru-terpi', 'Ceļotājs', '/kostimi/profesijas/celotajs.jpg', 920),
  ('animatoru-terpi', 'Cietumnieks', '/kostimi/profesijas/cietumnieks.jpg', 930),
  ('animatoru-terpi', 'Cowboy', '/kostimi/profesijas/cowboy-puisis.jpg', 940),
  ('animatoru-terpi', 'Dullais Profesors', '/kostimi/profesijas/dullais-profesors.jpg', 950),
  ('animatoru-terpi', 'Kapteinis', '/kostimi/profesijas/Kapteinis.jpg', 960),
  ('animatoru-terpi', 'Kosmonauts', '/kostimi/profesijas/kosmonauts.jpg', 970),
  ('animatoru-terpi', 'Skolotājs', '/kostimi/profesijas/macitajs.jpg', 980),
  ('animatoru-terpi', 'Medmāsa', '/kostimi/profesijas/medmasas-kostims.jpg', 990),
  ('animatoru-terpi', 'Policists', '/kostimi/profesijas/Policists.jpg', 1000),
  ('animatoru-terpi', 'Policiste', '/kostimi/profesijas/Policiste.jpg', 1010),
  ('animatoru-terpi', 'Grinčs', '/kostimi/ziemassvetki/grincs.jpg', 1020),
  ('animatoru-terpi', 'Ziemassvētku vecītis', '/kostimi/ziemassvetki/ziemassvetku-vecitis.jpg', 1030),
  ('animatoru-terpi', 'Rūķis', '/kostimi/ziemassvetki/rukis-smaidulis.jpg', 1040),
  ('animatoru-terpi', 'Eglīte', '/kostimi/ziemassvetki/egle.jpg', 1050),
  ('animatoru-terpi', 'Smieklīgais tēls 1', '/kostimi/smiekligi-teli/IMG_6517.jpg', 1060),
  ('animatoru-terpi', 'Smieklīgais tēls 2', '/kostimi/smiekligi-teli/IMG_6518.jpg', 1070),
  ('animatoru-terpi', 'Smieklīgais tēls 3', '/kostimi/smiekligi-teli/IMG_6832.jpg', 1080),
  ('animatoru-terpi', 'Smieklīgais tēls 4', '/kostimi/smiekligi-teli/IMG_6833.jpg', 1090)
) as seed (section_key, title, image_url, sort_order)
where not exists (
  select 1 from public.section_items where section_key = 'animatoru-terpi'
);
